global:
  scrape_interval: 15s #at what interval to pull/scrape the information from the service endpoint

scrape_configs:
  - job_name: "spring-ai-app" #job name
    metrics_path: "/actuator/prometheus" #endpoint from where we take the metrics
    static_configs:
      - targets: ["host.docker.internal:8080"] # -> http://localhost:8080 we can add here all ip addresses